### ISSUE TITLE
Runtime exception on dashboard getProxyData

### ISSUE THREAD

**Issue by alfredjkwak** [Digipalvelutehdas/APIKA#178]
```
=> Starting app on port 3000...
{"line":"106","file":"percolate_migrations.js","message":"Migrations: Not migrating, already at version 2","time":{"$date":1482167053954},"level":"info"}
spiderable: phantomjs not installed. Download and install from http://phantomjs.org/
Exception while invoking method 'getProxyData' TypeError: Cannot read property '0' of undefined
    at [object Object].getProxyData (dashboard/server/methods.js:25:39)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    at packages/ddp-server/livedata_server.js:551:43
```

Helpfult hint: Check proxyBackend has apiUmbrella object before using it https://github.com/Digipalvelutehdas/APIKA/blob/fec765d2deaa23dba58402a4cc3b2617709bc6a0/dashboard/server/methods.js#L25

**Comment by bajiat** [comment]
# Steps to reproduce
1. Log into apika.digipalvelutehdas.fi as admin
2. Go to dashboard
3. Go to Select API list and select one API

Repeat step nr. 3 until you get 504 Gateway Time-out

Cannot tell yet whether it is a certain API that causes this or a certain nr of selections.

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2040
